# Generated by Django 5.1.15 on 2026-07-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.CharField(help_text='Page ID (e.g. landing, about, placements, testimonials)', max_length=255, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict, help_text='Dynamic layout copy and media URL configurations')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
